function show_plate(experiment)
%Plotting function for structs generated by img_analysis.m

    figure, imshow(imadjust(rgb2gray(experiment.image))); hold on
    grid = experiment.grid;
    
    for r = 1:size(grid,1)
        for c = 1:size(grid,2)
            squarePts = [grid(r,c).tl;grid(r,c).tr;grid(r,c).br;grid(r,c).bl;grid(r,c).tl];
            plot(squarePts(:,1),squarePts(:,2),'r')
            viscircles(grid(r,c).centers, grid(r,c).radii);
        end
    end

end

